# Generated by Django 3.1.2 on 2020-10-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_auto_20201022_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(upload_to='newspaper/%Y/%m/%d/'),
        ),
    ]
